POST http://localhost:8080/
Content-Type: application/json

{
  "title": "Zrobić zadanie domowe!",
  "author": "Kamil",
  "date": "2019-11-25"
}

###

GET http://localhost:8080/
Accept: application/json

###