POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Zrobić zadanie domowe! 1",
  "description": "Zadanie 6"
}

###
PUT http://localhost:8080/api/tasks/1
Content-Type: application/json

{
  "title": "Z 1",
  "description": "Zadantie 6"
}

###

GET http://localhost:8080/api/tasks
Accept: application/json

###

GET http://localhost:8080/api/tasks?title=danie
Accept: application/json
###

DELETE http://localhost:8080/api/tasks/1
Accept: application/json

###

PUT localhost:8080/api/tasks/3
Content-Type: application/json

{
  "title": "Zadaie 0",
  "description": "Nadpisanie 2"
}

###

POST http://localhost:8080/api/tasks/2/tags
Content-Type: application/json

{
  "tagId": "2"
}
###